name: object_recognition
description: "TensorFlow Lite provides an API for image classification using the MobileNet model."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  image: ^4.1.7
  mockito: ^5.4.4
  tflite_flutter: ^0.10.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/tensor_flow_lite/
