name: object_recognition
description: "TensorFlow Lite provides an API for image classification using the MobileNet model."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  camera: ^0.10.5+9
  image: ^4.1.7
  mockito: ^5.4.4
  tflite_flutter: ^0.10.4
  equatable: any

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true 
  ios: true
  adaptive_icon_background: "#252525"
  adaptive_icon_foreground: "assets/images/adaptiveicon.png" 
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/tensor_flow_lite/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Light.ttf
